= Аннотация

Комплект инструментов {rk} предназначен для применения в организациях, эксплуатирующих систему {dv}.

{rk} содержит набор системных утилит различного назначения, предназначенных для специалистов {dv}.

.{rk} включает следующие программы:
. _{dv} 5 ActivationUtil_ -- программа для активации системы {dv}. Предоставляет следующие функции:
+
* Выполнение онлайн и офлайн активации лицензии {dv}.
* Отображение информации о текущей лицензии.
+
. _{dv} 5 CardManager_ -- программа для создания и регистрации схем метаданных библиотек карточек.
+
."CardManager" предоставляет следующие функции:
+
* Создание схем метаданных библиотек карточек.
* Создание схем метаданных карточек.
* Загрузка разработанных схем метаданных в БД {dv}.
+
. _{dv} 5 ChangeAccount_ -- программа для обновления данных учетных записей пользователей {dv}.
+
."{dv} 5 ChangeAccount" предоставляет следующие функции:
* Обновление данных учетных записей и дескрипторов безопасности в БД {dv} (в _Справочнике сотрудников_ и в системных таблицах) после переименования учетных записей и/или изменения домена.
* Удаление неиспользуемых дескрипторов безопасности.
+
. _{dv} 5 DVExplorer_ -- программа для работы с данными {dv} на низком уровне.
+
."{dv} 5 DVExplorer" предоставляет следующие функции:
* Просмотр/изменение данных карточек {dv}.
* Формирование и выполнение поисковых запросов.
* Получение детальной информации о типах карточек, загруженных в БД {dv}.
* Управление блокировками и др.
+
. _{dv} 5 LogViewer_ -- программа для просмотра журналов работы {dv}.
+
."{dv} 5 LogViewer" предоставляет следующие функции:
* Просмотр журналов (системы, безопасности, приложения) из файлов и/или из базы данных.
* Сортировка и фильтрация данных.
+
. _{dv} 5 SearchUtil_ -- программа для интерпретации поискового запроса {dv} из XML в SQL код.
. _{dv} 5 TOPartnersLoad_ -- программа для загрузки данных в _Справочник контрагентов_ из файлов формата `.xls`.
. _{dv} 5 TOStaffLoad_ -- программа для загрузки данных в _Справочник сотрудников_ из файлов формата `.xls`.
. _{dv} 5 ViewUtil_ -- программа для интерпретации кода представления (папки) {dv} из XML в SQL код.
. _{dv} 5 WindowsClient LogParser_ -- программа для конвертации журнала работы {wincl}а в файл `.xls`.
