= Аннотация

Комплект инструментов {rk} предназначен для применения в организациях, эксплуатирующих систему {dv}.

{rk} содержит набор системных утилит различного назначения, предназначенных для специалистов {dv}.

{rk} включает следующие программы:

. "{dv} 5 ActivationUtil" – программа для активации системы {dv}. Предоставляет следующие функции:
* выполнение онлайн и офлайн активации лицензии {dv};
* отображение информации о текущей лицензии.
. "{dv} 5 CardManager" – программа для создания и регистрации схем метаданных библиотек карточек. Предоставляет следующие функции:
* создание схем метаданных библиотек карточек;
* создание схем метаданных карточек;
* загрузка разработанных схем метаданных в БД {dv}.
. "{dv} 5 ChangeAccount" – программа для обновления данных учетных записей пользователей {dv}. Предоставляет следующие функции:
* обновление данных учетных записей и дескрипторов безопасности в БД {dv} (в _Справочнике сотрудников_ и в системных таблицах) после переименования учетных записей и/или изменения домена;
* удаление неиспользуемых дескрипторов безопасности.
. "{dv} 5 DVExplorer" – программа для работы с данными {dv} на низком уровне. Предоставляет следующие функции:
* просмотр/изменение данных карточек {dv};
* формирование и выполнение поисковых запросов;
* получение детальной информации о типах карточек, загруженных в БД {dv};
* управление блокировками и др.
. "{dv} 5 LogViewer" – программа для просмотра журналов работы {dv}. Предоставляет следующие функции:
* просмотр журналов (системы, безопасности, приложения) из файлов и/или из базы данных;
* сортировка и фильтрация данных.
. "{dv} 5 SearchUtil" – программа для интерпретации поискового запроса {dv} из XML в SQL код.
. "{dv} 5 TOPartnersLoad" – программа для загрузки данных в _Справочник контрагентов_ из файлов формата *.xls.
. "{dv} 5 TOStaffLoad" – программа для загрузки данных в _Справочник сотрудников_ из файлов формата *.xls.
. "{dv} 5 ViewUtil" – программа для интерпретации кода представления (папки) {dv} из XML в SQL код.
. "{dv} 5 WindowsClient LogParser" – программа для конвертации журнала работы Windows-клиента в файл *.xls.