= Загрузка данных в Справочник контрагентов

.Чтобы загрузить данные в _Справочник контрагентов_, выполните следующие действия:
. Запустите программу _TOPartnersLoad_.
. Заполните параметры:
.. В поле _URL сервиса_ укажите адрес сервера {dv} в формате `\http://Адрес-сервера-{dv}/{dv}/StorageServer/StorageServerService.asmx`.
.. В поле _Имя БД_ укажите имя БД {dv}, в которую будет производиться импорт данных. Оставьте поле пустым, чтобы импортировать данные в БД по умолчанию.
.. В поле _Файл MS Excel_ укажите путь к файлу `.xls` с загружаемыми данными.
.. Чтобы прекратить выполнение программы при обнаружении некорректных данных, установите флаг `*Останавливать загрузку при ошибках*`.
.. Чтобы, в случае совпадения уже имеющихся в справочнике и вновь вносимых в него названий организаций или фамилий сотрудников, заменить устаревшие сведения на новые, установите флаг `*Заменять существующие данные*`. Если флаг не установлен, в аналогичном случае система выдаст сообщение об ошибке.
. Для начала импорта нажмите кнопку *Загрузить*.
+
Результаты импорта данных будут отображены в поле _Результаты загрузки_.
