= Загрузка данных в Справочник сотрудников

.Чтобы загрузить данные в _Справочник сотрудников_:
. Запустите программу _TOStaffLoad_.
. Заполните параметры:
.. В поле _URL сервиса_ укажите адрес сервера {dv} в формате `\http://docsvision.server.com:5000/StorageServer/StorageServerService.asmx`.
.. В поле _Имя БД_ укажите имя БД {dv}, в которую будет производиться импорт данных. Оставьте поле пустым, чтобы импортировать данные в БД по умолчанию.
.. В поле _Файл MS Excel_ укажите путь к файлу `.xls` с загружаемыми данными.
.. В списке _Маршрутизация по умолчанию_ выберите тип маршрутизации, который будет указан в карточке сотрудника, если тип маршрутизации не указан в загружаемых данных.
.. Выберите учетные записи администратора {dv}, СУБП и группы подразделения в полях _Администратор_, _Сервер WF_ и _Группа для подразделений_. Указанным учетным записям будут предоставлены права на личные папки пользователей и папки подразделений. Обязательным к заполнению является поле _Администратор_.
.. Чтобы прекратить выполнение программы при обнаружении некорректных данных, установите флаг `*Останавливать загрузку при ошибках*`.
.. Чтобы импортировать только таблицы с информацией о сотрудниках организации, если структура организации уже создана в _Справочнике сотрудников_ вручную или ранее также путем импорта из аналогичного файла `.xls`, установите флаг `*Загружать только сотрудников*`. В противном случае процедура будет прервана, поскольку карточки сотрудников не могут добавляться в корневой элемент дерева справочника.
.. Чтобы, в случае совпадения уже имеющихся в _Справочнике сотрудников_ и вновь вносимых в него названий организаций или фамилий сотрудников, заменить устаревшие сведения на новые, установите флаг `*Заменять существующие данные*`. Если флаг снят, система выдаст сообщение об ошибке при обнаружении дублируемых записей.
. Для начала импорта нажмите кнопку *Загрузить*.
+
Результаты импорта данных будут отображены в поле _Результаты загрузки_.
