= Выгрузка

. Выберите файл или файлы журнала работы {wincl}а.
. Если необходимо, измените путь для формирования XLS-файла.
. Выберите промежуток времени, из которого будут выбраны экспортируемые события. Если начальная и конечная даты не указаны, будут выбраны все записи.
. Нажмите кнопку *Обработать* и дождитесь завершения. Для прекращения экспорта, нажмите кнопку *Остановить*.
+
В результате будет сформирован XLS-файл следующего формата:

[cols=",,,,,",]
|===
|Дата |Время |Операция |Объект |Длительность |Файл
|12.04.2016 |11:58:26 |Navigator started | | |Navigator.log
|12.04.2016 |11:58:30 |Folder expand |Папки (ffffffff-ffff-0003-ffff-000000000000) |0.006998 |Navigator.log
|12.04.2016 |11:58:31 |Navigator start | |4.8491848 |Navigator.log
|===

Файл содержит информацию о дате и времени совершения определенной операции (например, открытие папки), её название и сведения об объекте, а также длительность её выполнения. В последний столбец записывается название файла журнала работы (для идентификации источника данной строки).
